export { default as About } from './index.jsx'
export { default as Resume } from './resume.jsx'
export { default as Projects } from './projects'
export { default as Contact } from './contactTemp'
export { default as Journey } from './journey'