const timeLineData1 = [
  {
    name: "Java",
    imgSrc: "src/assets/java.png",
    color: "#D43609",
    date: "Mar 2023",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 0.25,
    left: "2.5rem",
  },
  {
    name: "HTML",
    imgSrc: "src/assets/html.png",
    color: "#F66B4E",
    date: "Mar 2024",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 0.5,
    left: "10rem",
  },
  {
    name: "CSS",
    imgSrc: "src/assets/css.png",
    color: "#45A8F2",
    date: "Apr 2024",
    bounceAnim: "animate-bounce-2",
    fadeDelay: 0.75,
    left: "17.5rem",
  },
];
const timeLineData2 = [
  {
    name: "JavaScript",
    imgSrc: "src/assets/javascript.png",
    color: "#F7DF1E",
    date: "May 2024",
    bounceAnim: "animate-bounce-3",
    fadeDelay: 0.25,
    left: "2.5rem",
  },
  {
    name: "PHP",
    imgSrc: "src/assets/php.png",
    color: "#777BB4",
    date: "Oct 2024",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 0.5,
    left: "10rem",
  },
  {
    name: "C#",
    imgSrc: "src/assets/csharp.png",
    color: "#8A2BE2",
    date: "Oct 2024",
    bounceAnim: "animate-bounce-2",
    fadeDelay: 0.75,
    left: "17.5rem",
  },
];
const timeLineData3 = [
  {
    name: "Python",
    imgSrc: "src/assets/python.png",
    color: "#3776AB",
    date: "Mar 2025",
    bounceAnim: "animate-bounce-3",
    fadeDelay: 0.25,
    left: "2.5rem",
  },
  {
    name: "Tailwind",
    imgSrc: "src/assets/tailwind-css.png",
    color: "#06B6D4",
    date: "May 2025",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 0.5,
    left: "10rem",
  },
  {
    name: "React",
    imgSrc: "src/assets/react.png",
    color: "#61DAFB",
    date: "May 2025",
    bounceAnim: "animate-bounce-2",
    fadeDelay: 0.75,
    left: "17.5rem",
  },
];

const timeLineData4 = [
  {
    name: "Next JS",
    imgSrc: "src/assets/nextjavascript.png",
    color: "#FFFFFF",
    date: "Next",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 0.25,
    left: "2.5rem",
  },
  {
    name: "TypeScript",
    imgSrc: "src/assets/typescript.png",
    color: "#3178C6",
    date: "Next",
    bounceAnim: "animate-bounce-2",
    fadeDelay: 0.5,
    left: "10rem",
  },
  {
    name: "Node JS",
    imgSrc: "src/assets/nodejavascript.png",
    color: "#98FB98",
    date: "Next",
    bounceAnim: "animate-bounce-3",
    fadeDelay: 0.75,
    left: "17.5rem",
  },
];

const timeLineData5 = [
  {
    name: "React Native",
    imgSrc: "src/assets/reactnative.webp",
    color: "#61DAFB",
    date: "Next",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 0.25,
    left: "2.5rem",
  },
  {
    name: "Dart",
    imgSrc: "src/assets/dart.png",
    color: "#00B4AB",
    date: "Next",
    bounceAnim: "animate-bounce-2",
    fadeDelay: 0.5,
    left: "10rem",
  },
  {
    name: "Flutter",
    imgSrc: "src/assets/flutter.png",
    color: "#02569B",
    date: "Next",
    bounceAnim: "animate-bounce-3",
    fadeDelay: 0.75,
    left: "17.5rem",
  },
];

const timeLineData6 = [
  {
    name: "Swift",
    imgSrc: "src/assets/swift.png",
    color: "#FA7343",
    date: "Next",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 0.25,
    left: "2.5rem",
  },
];

const timeLineDataAtSM = [
  {
    name: "Java",
    imgSrc: "src/assets/java.png",
    color: "#D43609",
    date: "Mar 2023",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 0.25,
    left: "2.5rem",
  },
  {
    name: "HTML",
    imgSrc: "src/assets/html.png",
    color: "#F66B4E",
    date: "Mar 2024",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 0.5,
    left: "10rem",
  },
  {
    name: "CSS",
    imgSrc: "src/assets/css.png",
    color: "#45A8F2",
    date: "Apr 2024",
    bounceAnim: "animate-bounce-2",
    fadeDelay: 0.75,
    left: "17.5rem",
  },
  {
    name: "JavaScript",
    imgSrc: "src/assets/javascript.png",
    color: "#F7DF1E",
    date: "May 2024",
    bounceAnim: "animate-bounce-3",
    fadeDelay: 1,
    left: "25rem",
  },
];

const timeLineDataAtSM2 = [
  {
    name: "PHP",
    imgSrc: "src/assets/php.png",
    color: "#777BB4",
    date: "Oct 2024",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 0.25,
    left: "2.5rem",
  },
  {
    name: "C#",
    imgSrc: "src/assets/csharp.png",
    color: "#8A2BE2",
    date: "Oct 2024",
    bounceAnim: "animate-bounce-2",
    fadeDelay: 0.5,
    left: "10rem",
  },
  {
    name: "Python",
    imgSrc: "src/assets/python.png",
    color: "#3776AB",
    date: "Mar 2025",
    bounceAnim: "animate-bounce-3",
    fadeDelay: 0.75,
    left: "17.5rem",
  },
  {
    name: "Tailwind",
    imgSrc: "src/assets/tailwind-css.png",
    color: "#06B6D4",
    date: "May 2024",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 1,
    left: "25rem",
  },
];

const timeLineDataAtSM3 = [
  {
    name: "React",
    imgSrc: "src/assets/react.png",
    color: "#61DAFB",
    date: "May 2025",
    bounceAnim: "animate-bounce-2",
    fadeDelay: 0.25,
    left: "2.5rem",
  },
  {
    name: "Next JS",
    imgSrc: "src/assets/nextjavascript.png",
    color: "#FFFFFF",
    date: "Next",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 0.5,
    left: "10rem",
  },
  {
    name: "TypeScript",
    imgSrc: "src/assets/typescript.png",
    color: "#3178C6",
    date: "Next",
    bounceAnim: "animate-bounce-2",
    fadeDelay: 0.75,
    left: "17.5rem",
  },
  {
    name: "Node JS",
    imgSrc: "src/assets/nodejavascript.png",
    color: "#98FB98",
    date: "Next",
    bounceAnim: "animate-bounce-3",
    fadeDelay: 1,
    left: "25rem",
  },
];

const timeLineDataAtSM4 = [
  {
    name: "React Native",
    imgSrc: "src/assets/reactnative.webp",
    color: "#61DAFB",
    date: "Next",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 0.25,
    left: "2.5rem",
  },
  {
    name: "Dart",
    imgSrc: "src/assets/dart.png",
    color: "#00B4AB",
    date: "Next",
    bounceAnim: "animate-bounce-2",
    fadeDelay: 0.5,
    left: "10rem",
  },
  {
    name: "Flutter",
    imgSrc: "src/assets/flutter.png",
    color: "#02569B",
    date: "Next",
    bounceAnim: "animate-bounce-3",
    fadeDelay: 0.75,
    left: "17.5rem",
  },
  {
    name: "Swift",
    imgSrc: "src/assets/swift.png",
    color: "#FA7343",
    date: "Next",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 1,
    left: "25rem",
  },
];

const timeLineDataAtMD = [
  ...timeLineDataAtSM,
  {
    name: "PHP",
    imgSrc: "src/assets/php.png",
    color: "#777BB4",
    date: "Oct 2024",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 1.25,
    left: "32.5rem",
  },
]

const timeLineDataAtMD2 = [
  {
    name: "C#",
    imgSrc: "src/assets/csharp.png",
    color: "#8A2BE2",
    date: "Oct 2024",
    bounceAnim: "animate-bounce-2",
    fadeDelay: 0.25,
    left: "2.5rem",
  },
  {
    name: "Python",
    imgSrc: "src/assets/python.png",
    color: "#3776AB",
    date: "Mar 2025",
    bounceAnim: "animate-bounce-3",
    fadeDelay: 0.5,
    left: "10rem",
  },
  {
    name: "Tailwind",
    imgSrc: "src/assets/tailwind-css.png",
    color: "#06B6D4",
    date: "May 2024",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 0.75,
    left: "17.5rem",
  },
  {
    name: "React",
    imgSrc: "src/assets/react.png",
    color: "#61DAFB",
    date: "May 2025",
    bounceAnim: "animate-bounce-2",
    fadeDelay: 1,
    left: "25rem",
  },
  {
    name: "Next JS",
    imgSrc: "src/assets/nextjavascript.png",
    color: "#FFFFFF",
    date: "Next",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 1.25,
    left: "32.5rem",
  },
];

const timeLineDataAtMD3 = [
  {
    name: "TypeScript",
    imgSrc: "src/assets/typescript.png",
    color: "#3178C6",
    date: "Next",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 0.25,
    left: "2.5rem",
  },
  {
    name: "Node JS",
    imgSrc: "src/assets/nodejavascript.png",
    color: "#98FB98",
    date: "Next",
    bounceAnim: "animate-bounce-2",
    fadeDelay: 0.5,
    left: "10rem",
  },
  {
    name: "React Native",
    imgSrc: "src/assets/reactnative.webp",
    color: "#61DAFB",
    date: "Next",
    bounceAnim: "animate-bounce-3",
    fadeDelay: 0.75,
    left: "17.5rem",
  },
  {
    name: "Dart",
    imgSrc: "src/assets/dart.png",
    color: "#00B4AB",
    date: "Next",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 1,
    left: "25rem",
  },
  {
    name: "Flutter",
    imgSrc: "src/assets/flutter.png",
    color: "#02569B",
    date: "Next",
    bounceAnim: "animate-bounce-2",
    fadeDelay: 1.25,
    left: "32.5rem",
  },
]

const timeLineDataAtMD4 = [
  {
    name: "Swift",
    imgSrc: "src/assets/swift.png",
    color: "#FA7343",
    date: "Next",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 0.25,
    left: "2.5rem",
  },
];

const timeLineDataAtLG = [
  {
    name: "Java",
    imgSrc: "src/assets/java.png",
    color: "#D43609",
    date: "Mar 2023",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 0.25,
    left: "2.5rem",
  },
  {
    name: "HTML",
    imgSrc: "src/assets/html.png",
    color: "#F66B4E",
    date: "Mar 2024",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 0.5,
    left: "9rem",
  },
  {
    name: "CSS",
    imgSrc: "src/assets/css.png",
    color: "#45A8F2",
    date: "Apr 2024",
    bounceAnim: "animate-bounce-2",
    fadeDelay: 0.75,
    left: "15.5rem",
  },
  {
    name: "JavaScript",
    imgSrc: "src/assets/javascript.png",
    color: "#F7DF1E",
    date: "May 2024",
    bounceAnim: "animate-bounce-3",
    fadeDelay: 1,
    left: "22rem",
  },
  {
    name: "PHP",
    imgSrc: "src/assets/php.png",
    color: "#777BB4",
    date: "Oct 2024",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 1.25,
    left: "28.5rem",
  },
  {
    name: "C#",
    imgSrc: "src/assets/csharp.png",
    color: "#8A2BE2",
    date: "Oct 2024",
    bounceAnim: "animate-bounce-2",
    fadeDelay: 1.5,
    left: "35rem",
  },
  {
    name: "Python",
    imgSrc: "src/assets/python.png",
    color: "#3776AB",
    date: "Mar 2025",
    bounceAnim: "animate-bounce-3",
    fadeDelay: 1.75,
    left: "41.5rem",
  },
  {
    name: "Tailwind",
    imgSrc: "src/assets/tailwind-css.png",
    color: "#06B6D4",
    date: "May 2024",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 2,
    left: "48rem",
  },
];

const timeLineDataAtLG2 = [
  {
    name: "React",
    imgSrc: "src/assets/react.png",
    color: "#61DAFB",
    date: "May 2025",
    bounceAnim: "animate-bounce-2",
    fadeDelay: 0.25,
    left: "2.5rem",
  },
  {
    name: "Next JS",
    imgSrc: "src/assets/nextjavascript.png",
    color: "#FFFFFF",
    date: "Next",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 0.5,
    left: "9rem",
  },
  {
    name: "TypeScript",
    imgSrc: "src/assets/typescript.png",
    color: "#3178C6",
    date: "Next",
    bounceAnim: "animate-bounce-2",
    fadeDelay: 0.75,
    left: "15.5rem",
  },
  {
    name: "Node JS",
    imgSrc: "src/assets/nodejavascript.png",
    color: "#98FB98",
    date: "Next",
    bounceAnim: "animate-bounce-3",
    fadeDelay: 1,
    left: "22rem",
  },
  {
    name: "React Native",
    imgSrc: "src/assets/reactnative.webp",
    color: "#61DAFB",
    date: "Next",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 1.25,
    left: "28.5rem",
  },
  {
    name: "Dart",
    imgSrc: "src/assets/dart.png",
    color: "#00B4AB",
    date: "Next",
    bounceAnim: "animate-bounce-2",
    fadeDelay: 1.5,
    left: "35rem",
  },
  {
    name: "Flutter",
    imgSrc: "src/assets/flutter.png",
    color: "#02569B",
    date: "Next",
    bounceAnim: "animate-bounce-3",
    fadeDelay: 1.75,
    left: "41.5rem",
  },
  {
    name: "Swift",
    imgSrc: "src/assets/swift.png",
    color: "#FA7343",
    date: "Next",
    bounceAnim: "animate-bounce-1",
    fadeDelay: 2,
    left: "48rem",
  },
]

const timeLineDataForFSD = [
  {
    name: "HTML",
    imgSrc: "src/assets/html.png",
    color: "#F66B4E",
    date: "Mar 2024",
    bounceAnim: "animate-bounce-1",
    hasPoint: false,
    fadeDelay: 0.25,
    left: "2.5rem",
  },
  {
    name: "CSS",
    imgSrc: "src/assets/css.png",
    color: "#45A8F2",
    date: "Apr 2024",
    bounceAnim: "animate-bounce-2",
    hasPoint: false,
    fadeDelay: 0.5,
    left: "10rem",
  },
  {
    name: "JavaScript",
    imgSrc: "src/assets/javascript.png",
    color: "#F7DF1E",
    date: "May 2024",
    bounceAnim: "animate-bounce-3",
    hasPoint: false,
    fadeDelay: 0.75,
    left: "17.5rem",
  },
]

const timeLineDataForFSD2 = [
  {
    name: "PHP",
    imgSrc: "src/assets/php.png",
    color: "#777BB4",
    date: "Oct 2024",
    bounceAnim: "animate-bounce-1",
    hasPoint: false,
    fadeDelay: 0.25,
    left: "2.5rem",
  },
  {
    name: "Tailwind",
    imgSrc: "src/assets/tailwind-css.png",
    color: "#06B6D4",
    date: "May 2024",
    bounceAnim: "animate-bounce-1",
    hasPoint: false,
    fadeDelay: 0.5,
    left: "10rem",
  },
  {
    name: "React",
    imgSrc: "src/assets/react.png",
    color: "#61DAFB",
    date: "May 2025",
    bounceAnim: "animate-bounce-2",
    hasPoint: false,
    fadeDelay: 0.75,
    left: "17.5rem",
  },
];

const timeLineDataForFSD3 = [
  {
    name: "Next JS",
    imgSrc: "src/assets/nextjavascript.png",
    color: "#FFFFFF",
    date: "Next",
    bounceAnim: "animate-bounce-1",
    hasPoint: false,
    fadeDelay: 0.25,
    left: "2.5rem",
  },
  {
    name: "TypeScript",
    imgSrc: "src/assets/typescript.png",
    color: "#3178C6",
    date: "Next",
    bounceAnim: "animate-bounce-2",
    hasPoint: false,
    fadeDelay: 0.5,
    left: "10rem",
  },
  {
    name: "Node JS",
    imgSrc: "src/assets/nodejavascript.png",
    color: "#98FB98",
    date: "Next",
    bounceAnim: "animate-bounce-3",
    hasPoint: false,
    fadeDelay: 0.75,
    left: "17.5rem",
  },
];

const timeLineDataForFSDAtSM = [
  ...timeLineDataForFSD,
  {
    name: "PHP",
    imgSrc: "src/assets/php.png",
    color: "#777BB4",
    date: "Oct 2024",
    bounceAnim: "animate-bounce-1",
    hasPoint: false,
    fadeDelay: 1,
    left: "25rem",
  },
];

const timeLineDataForFSDAtSM2 = [
  {
    name: "Tailwind",
    imgSrc: "src/assets/tailwind-css.png",
    color: "#06B6D4",
    date: "May 2024",
    bounceAnim: "animate-bounce-1",
    hasPoint: false,
    fadeDelay: 0.25,
    left: "2.5rem",
  },
  {
    name: "React",
    imgSrc: "src/assets/react.png",
    color: "#61DAFB",
    date: "May 2025",
    bounceAnim: "animate-bounce-2",
    hasPoint: false,
    fadeDelay: 0.5,
    left: "10rem",
  },
  {
    name: "Next JS",
    imgSrc: "src/assets/nextjavascript.png",
    color: "#FFFFFF",
    date: "Next",
    bounceAnim: "animate-bounce-1",
    hasPoint: false,
    fadeDelay: 0.75,
    left: "17.5rem",
  },
  {
    name: "TypeScript",
    imgSrc: "src/assets/typescript.png",
    color: "#3178C6",
    date: "Next",
    bounceAnim: "animate-bounce-2",
    hasPoint: false,
    fadeDelay: 1,
    left: "25rem",
  },
];

const timeLineDataForFSDAtSM3 = [
  {
    name: "Node JS",
    imgSrc: "src/assets/nodejavascript.png",
    color: "#98FB98",
    date: "Next",
    bounceAnim: "animate-bounce-3",
    hasPoint: false,
    fadeDelay: 0.25,
    left: "2.5rem",
  },
];

const timeLineDataForFSDAtMD = [
  ...timeLineDataForFSDAtSM,
  {
    name: "Tailwind",
    imgSrc: "src/assets/tailwind-css.png",
    color: "#06B6D4",
    date: "May 2024",
    bounceAnim: "animate-bounce-1",
    hasPoint: false,
    fadeDelay: 1.25,
    left: "32.5rem",
  },
];

const timeLineDataForFSDAtMD2 = [
  {
    name: "React",
    imgSrc: "src/assets/react.png",
    color: "#61DAFB",
    date: "May 2025",
    bounceAnim: "animate-bounce-2",
    hasPoint: false,
    fadeDelay: 0.25,
    left: "2.5rem",
  },
  {
    name: "Next JS",
    imgSrc: "src/assets/nextjavascript.png",
    color: "#FFFFFF",
    date: "Next",
    bounceAnim: "animate-bounce-1",
    hasPoint: false,
    fadeDelay: 0.5,
    left: "10rem",
  },
  {
    name: "TypeScript",
    imgSrc: "src/assets/typescript.png",
    color: "#3178C6",
    date: "Next",
    bounceAnim: "animate-bounce-2",
    hasPoint: false,
    fadeDelay: 0.75,
    left: "17.5rem",
  },
  {
    name: "Node JS",
    imgSrc: "src/assets/nodejavascript.png",
    color: "#98FB98",
    date: "Next",
    bounceAnim: "animate-bounce-3",
    hasPoint: false,
    fadeDelay: 1,
    left: "25rem",
  },
];

const timeLineDataForFSDAtLG = [
  {
    name: "HTML",
    imgSrc: "src/assets/html.png",
    color: "#F66B4E",
    date: "Mar 2024",
    bounceAnim: "animate-bounce-1",
    hasPoint: false,
    fadeDelay: 0.25,
    left: "2.5rem",
  },
  {
    name: "CSS",
    imgSrc: "src/assets/css.png",
    color: "#45A8F2",
    date: "Apr 2024",
    bounceAnim: "animate-bounce-2",
    hasPoint: false,
    fadeDelay: 0.5,
    left: "9rem",
  },
  {
    name: "JavaScript",
    imgSrc: "src/assets/javascript.png",
    color: "#F7DF1E",
    date: "May 2024",
    bounceAnim: "animate-bounce-3",
    hasPoint: false,
    fadeDelay: 0.75,
    left: "15.5rem",
  },
  {
    name: "PHP",
    imgSrc: "src/assets/php.png",
    color: "#777BB4",
    date: "Oct 2024",
    bounceAnim: "animate-bounce-1",
    hasPoint: false,
    fadeDelay: 1,
    left: "22rem",
  },
  {
    name: "Tailwind",
    imgSrc: "src/assets/tailwind-css.png",
    color: "#06B6D4",
    date: "May 2024",
    bounceAnim: "animate-bounce-2",
    hasPoint: false,
    fadeDelay: 1.25,
    left: "28.5rem",
  },
  {
    name: "React",
    imgSrc: "src/assets/react.png",
    color: "#61DAFB",
    date: "May 2025",
    bounceAnim: "animate-bounce-3",
    hasPoint: false,
    fadeDelay: 1.5,
    left: "35rem",
  },
  {
    name: "Next JS",
    imgSrc: "src/assets/nextjavascript.png",
    color: "#FFFFFF",
    date: "Next",
    bounceAnim: "animate-bounce-1",
    hasPoint: false,
    fadeDelay: 1.75,
    left: "41.5rem",
  },
  {
    name: "TypeScript",
    imgSrc: "src/assets/typescript.png",
    color: "#3178C6",
    date: "Next",
    bounceAnim: "animate-bounce-2",
    hasPoint: false,
    fadeDelay: 2,
    left: "48rem",
  },
];

const timeLineDataForFSDAtLG2 = [
  {
    name: "Node JS",
    imgSrc: "src/assets/nodejavascript.png",
    color: "#98FB98",
    date: "Next",
    bounceAnim: "animate-bounce-3",
    hasPoint: false,
    fadeDelay: 0.25,
    left: "2.5rem",
  },
];

const timeLineDataForADV = [
  {
    name: "React Native",
    imgSrc: "src/assets/reactnative.webp",
    color: "#61DAFB",
    date: "Next",
    bounceAnim: "animate-bounce-1",
    hasPoint: false,
    fadeDelay: 0.25,
    left: "2.5rem",
  },
  {
    name: "Dart",
    imgSrc: "src/assets/dart.png",
    color: "#00B4AB",
    date: "Next",
    bounceAnim: "animate-bounce-2",
    hasPoint: false,
    fadeDelay: 0.5,
    left: "10rem",
  },
  {
    name: "Flutter",
    imgSrc: "src/assets/flutter.png",
    color: "#02569B",
    date: "Next",
    bounceAnim: "animate-bounce-3",
    hasPoint: false,
    fadeDelay: 0.75,
    left: "17.5rem",
  },
];

const timeLineDataForADV2 = [
  {
    name: "Java",
    imgSrc: "src/assets/java.png",
    color: "#D43609",
    date: "Mar 2023",
    bounceAnim: "animate-bounce-1",
    hasPoint: false,
    fadeDelay: 0.25,
    left: "2.5rem",
  },
  {
    name: "Swift",
    imgSrc: "src/assets/swift.png",
    color: "#FA7343",
    date: "Next",
    bounceAnim: "animate-bounce-2",
    hasPoint: false,
    fadeDelay: 0.5,
    left: "10rem",
  },
]

const timeLineDataForADVAtSM = [
  ...timeLineDataForADV,
  {
    name: "Java",
    imgSrc: "src/assets/java.png",
    color: "#D43609",
    date: "Mar 2023",
    bounceAnim: "animate-bounce-1",
    hasPoint: false,
    fadeDelay: 1,
    left: "25rem",
  },
];

const timeLineDataForADVAtSM2 = [
  {
    name: "Swift",
    imgSrc: "src/assets/swift.png",
    color: "#FA7343",
    date: "Next",
    bounceAnim: "animate-bounce-1",
    hasPoint: false,
    fadeDelay: 0.25,
    left: "2.5rem",
  },
]

const timeLineDataForADVAtMD = [
  ...timeLineDataForADVAtSM,
  {
    name: "Swift",
    imgSrc: "src/assets/swift.png",
    color: "#FA7343",
    date: "Next",
    bounceAnim: "animate-bounce-1",
    hasPoint: false,
    fadeDelay: 1.25,
    left: "32.5rem",
  },
];

const timeLineDataForADVAtLG = [
  ...timeLineDataForADVAtMD,
];

export {
  timeLineData1, timeLineData2, timeLineData3, timeLineData4, timeLineData5, timeLineData6,
  timeLineDataAtSM, timeLineDataAtSM2, timeLineDataAtSM3, timeLineDataAtSM4,
  timeLineDataAtMD, timeLineDataAtMD2, timeLineDataAtMD3, timeLineDataAtMD4,
  timeLineDataAtLG, timeLineDataAtLG2,
  timeLineDataForFSD, timeLineDataForFSD2, timeLineDataForFSD3,
  timeLineDataForFSDAtSM, timeLineDataForFSDAtSM2, timeLineDataForFSDAtSM3,
  timeLineDataForFSDAtMD, timeLineDataForFSDAtMD2,
  timeLineDataForFSDAtLG, timeLineDataForFSDAtLG2,
  timeLineDataForADV, timeLineDataForADV2,
  timeLineDataForADVAtSM, timeLineDataForADVAtSM2,
  timeLineDataForADVAtMD,
  timeLineDataForADVAtLG,
};
